-- liquibase formatted sql

--changeset valentinkd3:1
CREATE TABLE IF NOT EXISTS data (
    id bigint generated by default as identity primary key,
    sensor_id bigint not null,
    timestamp timestamp not null,
    measurement float not null,
    type varchar(32) not null
)